[package]
name = "denests"
version = "0.1.0"
authors = ["Kevin Amado <kamadorueda@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
serde = { version = "1.0.16", features = ["derive"] }
serde_derive = "1.0.116"
serde_json = "1.0"
uuid = { version = "0.4", features = ["v4"] }
